# Generated by Django 6.0.6 on 2026-07-28 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور خرید')),
                ('brand', models.CharField(max_length=100, verbose_name='برند باتری')),
                ('amperage', models.IntegerField(verbose_name='آمپر باتری')),
                ('quantity', models.IntegerField(verbose_name='تعداد خریداری شده')),
                ('purchase_price_per_amper', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت خرید هر آمپر')),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='برند باتری')),
                ('amperage', models.IntegerField(verbose_name='آمپر')),
                ('purchase_price_per_amper', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت خرید هر آمپر')),
                ('serial_code', models.CharField(max_length=100, unique=True, verbose_name='کد/سریال اختصاصی باتری')),
                ('status', models.CharField(choices=[('available', 'موجود در انبار'), ('sold', 'فروخته شده'), ('returned', 'مرجوعی')], default='available', max_length=20, verbose_name='وضعیت')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='battery.purchase', verbose_name='فاکتور خرید مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن مشتری')),
                ('car_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک ماشین')),
                ('warranty_serial', models.CharField(max_length=100, verbose_name='سریال گارانتی')),
                ('daghi_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ داغی تحویل گرفته شده (تومان)')),
                ('installer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شخص نصاب')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فروش')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battery.battery', verbose_name='کد/سریال باتری فروخته شده')),
            ],
        ),
    ]
