# Generated by Django 6.0.6 on 2026-07-28 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'برند باتری',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور خرید')),
                ('date_purchased', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daghi_price_per_amper', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت خرید روز داغی (هر آمپر)')),
                ('default_profit_percent', models.IntegerField(default=20, verbose_name='درصد سود پیش\u200cفرض فروش')),
            ],
            options={
                'verbose_name': 'تنظیمات قیمت داغی و سود',
                'verbose_name_plural': 'تنظیمات پایه سیستم',
            },
        ),
        migrations.RemoveField(
            model_name='battery',
            name='purchase',
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name': 'باتری انبار', 'verbose_name_plural': 'موجودی باتری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'فروش باتری', 'verbose_name_plural': 'فاکتورهای فروش'},
        ),
        migrations.RemoveField(
            model_name='battery',
            name='purchase_price_per_amper',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='daghi_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='installer_name',
        ),
        migrations.AddField(
            model_name='battery',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='قیمت خرید کل (تومان)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='daghi_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کسر شده داغی'),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی دریافتی'),
        ),
        migrations.AddField(
            model_name='sale',
            name='has_daghi',
            field=models.BooleanField(default=True, verbose_name='تحویل داغی دارد؟'),
        ),
        migrations.AddField(
            model_name='sale',
            name='installer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نصاب / فروشنده'),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سود این فروش'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price_without_daghi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش بدون داغی'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='serial_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد کوتاه باتری'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='status',
            field=models.CharField(choices=[('available', 'موجود در انبار'), ('sold', 'فروخته شده')], default='available', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battery.battery', verbose_name='انتخاب باتری از انبار'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن مشتری'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ فروش'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battery.brand', verbose_name='برند'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperage', models.IntegerField(verbose_name='آمپر')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('purchase_price_per_amper', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت خرید هر آمپر (تومان)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battery.brand', verbose_name='برند')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='battery.purchaseinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم خرید',
                'verbose_name_plural': 'آیتم\u200cهای خرید',
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='purchase_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='battery.purchaseitem'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
