# Generated by Django 6.0.6 on 2026-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_brand_purchaseinvoice_systemsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='selling_price_per_amper',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت فروش روز هر آمپر (تومان)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='قیمت خرید واقعی فاکتور (تومان)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سود واقعی این فروش'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price_without_daghi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت فروش روز بدون داغی'),
        ),
    ]
