# Generated by Django 6.0.6 on 2026-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_brand_selling_price_per_amper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='amperage',
            field=models.CharField(max_length=10, verbose_name='آمپر'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='amperage',
            field=models.CharField(choices=[('50L1', '50L1'), ('50L2', '50L2'), ('55', '55'), ('60', '60'), ('66', '66'), ('70', '70'), ('74', '74')], default='50L1', max_length=10, verbose_name='آمپر'),
        ),
    ]
