# Generated by Django 6.0.6 on 2026-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0004_alter_battery_amperage_alter_purchaseitem_amperage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='profit',
        ),
    ]
