# Generated by Django 6.0.6 on 2026-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0005_remove_sale_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='daghi_amperage',
            field=models.CharField(blank=True, choices=[('50', '50 آمپر'), ('55', '55 آمپر'), ('60', '60 آمپر'), ('66', '66 آمپر'), ('70', '70 آمپر'), ('74', '74 آمپر'), ('90', '90 آمپر'), ('100', '100 آمپر')], help_text='اگر خالی بماند، به صورت خودکار برابر با آمپر باتری نو محاسبه می\u200cشود.', max_length=10, null=True, verbose_name='آمپر داغی تحویلی (در صورت متفاوت بودن)'),
        ),
    ]
