# Generated by Django 6.0.6 on 2026-07-28 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0006_sale_daghi_amperage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مبلغ تخفیف دستی که از فاکتور کسر می\u200cشود', max_digits=12, verbose_name='مبلغ تخفیف (تومان)'),
        ),
    ]
