# Generated by Django 6.0.6 on 2026-07-28 19:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0007_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سود حاصل از فروش'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='مبلغ تخفیف دستی (تومان)'),
        ),
    ]
