# Generated by Django 6.0.6 on 2026-07-28 19:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0008_sale_profit_alter_sale_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='profit',
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مبلغ تخفیفی که دستی از فاکتور کسر می\u200cشود', max_digits=12, verbose_name='مبلغ تخفیف (تومان)'),
        ),
    ]
