# Generated by Django 6.0.6 on 2026-07-30 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0009_remove_sale_profit_alter_sale_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='installation_fee',
            field=models.DecimalField(decimal_places=0, default=250000, max_digits=10, verbose_name='اجرت نصب پایه (تومان)'),
        ),
        migrations.CreateModel(
            name='InstallerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'درآمد اجرت (بستانکار)'), ('payout', 'تسویه حساب (بدهکار)')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='نصاب')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battery.sale', verbose_name='بابت فاکتور')),
            ],
            options={
                'verbose_name': 'تراکنش نصاب',
                'verbose_name_plural': 'کیف پول نصاب\u200cها',
            },
        ),
    ]
