# Generated by Django 6.0.6 on 2026-08-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0010_systemsetting_installation_fee_installertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='روش پرداخت (مثل: کارتخوان، نقدی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battery.paymentmethod', verbose_name='روش پرداخت'),
        ),
    ]
