# Generated by Django 6.0.6 on 2026-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0011_paymentmethod_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='amperage',
            field=models.CharField(choices=[('50L1', '50L1'), ('50L2', '50L2'), ('55', '55'), ('60', '60'), ('66', '66'), ('70L', '70L'), ('70R', '70R'), ('74', '74')], default='50L1', max_length=10, verbose_name='آمپر'),
        ),
    ]
