# Generated by Django 6.0.6 on 2026-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0012_alter_purchaseitem_amperage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت خرید واقعی فاکتور (تومان)'),
        ),
    ]
