# Generated by Django 6.0.6 on 2026-08-12 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0013_alter_battery_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='battery.purchaseitem'),
        ),
    ]
