# Generated by Django 6.0.6 on 2026-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0014_alter_battery_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل ماشین'),
        ),
    ]
