# Generated by Django 6.0.6 on 2026-09-02 22:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0016_sale_warranty_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='surcharge',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مبالغ افزوده شده بابت خدمات جانبی، ایاب\u200cوذهاب و...', max_digits=12, verbose_name='اضافه\u200cبها / خدمات مازاد (تومان)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='daghi_amperage',
            field=models.CharField(blank=True, choices=[('50', '50 آمپر'), ('55', '55 آمپر'), ('60', '60 آمپر'), ('66', '66 آمپر'), ('70', '70 آمپر'), ('74', '74 آمپر'), ('90', '90 آمپر'), ('100', '100 آمپر')], help_text='اگر خالی بماند، برابر با آمپر باتری نو محاسبه می\u200cشود.', max_length=10, null=True, verbose_name='آمپر داغی تحویلی (در صورت متفاوت بودن)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='مبلغ تخفیف کسر شده از فاکتور', max_digits=12, verbose_name='مبلغ تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نصاب / فروشنده'),
        ),
    ]
