# Generated by Django 6.0.6 on 2026-09-03 16:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0017_sale_surcharge_alter_sale_daghi_amperage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='daghi_received_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), help_text='مبلغ داغی که در فرم ثبت یا ویرایش شده است', max_digits=12, null=True, verbose_name='مبلغ داغی دریافتی (تومان)'),
        ),
    ]
